// Generated by FlowBuilder
import React from 'react';

export default function ModernLandingPageCopyPage() {
    return (
        <div className="min-h-screen bg-gray-50 p-8">
            <div className="max-w-4xl mx-auto">
      <div className="flex flex-col gap-4 p-40 ">

      </div>
      <p style={{ fontSize: 48 }}>Build Amazing Products</p>
      <p style={{ fontSize: 20 }}>The visual builder for modern developers</p>
      <button className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors">Get Started</button>
            </div>
        </div>
    );
}
